name: Commitlint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Lint commit messages (pull request)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }}

      - name: Lint commit messages (push)
        if: github.event_name == 'push'
        run: npx commitlint --from ${{ github.event.before }}
